//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 03:34:16 PM CEST 
//


package com.orange.jlinx.document.x;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.orange.jlinx.document.x package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("", "Document");
    private final static QName _Medication_QNAME = new QName("http://indivo.org/vocab/xml/documents#", "Medication");
    private final static QName _Problem_QNAME = new QName("http://indivo.org/vocab/xml/documents#", "Problem");
    private final static QName _Account_QNAME = new QName("", "Account");
    private final static QName _Allergy_QNAME = new QName("http://indivo.org/vocab/xml/documents#", "Allergy");
    private final static QName _VitalSign_QNAME = new QName("http://indivo.org/vocab/xml/documents#", "VitalSign");
    private final static QName _Record_QNAME = new QName("", "Record");
    private final static QName _Equipment_QNAME = new QName("http://indivo.org/vocab/xml/documents#", "Equipment");
    private final static QName _Documents_QNAME = new QName("", "Documents");
    private final static QName _Ok_QNAME = new QName("", "ok");
    private final static QName _Immunization_QNAME = new QName("http://indivo.org/vocab/xml/documents#", "Immunization");
    private final static QName _DocumentStatusHistory_QNAME = new QName("", "DocumentStatusHistory");
    private final static QName _Procedure_QNAME = new QName("http://indivo.org/vocab/xml/documents#", "Procedure");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.orange.jlinx.document.x
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XReports }
     * 
     */
    public XReports createXReports() {
        return new XReports();
    }

    /**
     * Create an instance of {@link XContact }
     * 
     */
    public XContact createXContact() {
        return new XContact();
    }

    /**
     * Create an instance of {@link XResultInSet }
     * 
     */
    public XResultInSet createXResultInSet() {
        return new XResultInSet();
    }

    /**
     * Create an instance of {@link XMicroWithCultureLabTest }
     * 
     */
    public XMicroWithCultureLabTest createXMicroWithCultureLabTest() {
        return new XMicroWithCultureLabTest();
    }

    /**
     * Create an instance of {@link XMicroWithCultureLabTest.Result }
     * 
     */
    public XMicroWithCultureLabTest.Result createXMicroWithCultureLabTestResult() {
        return new XMicroWithCultureLabTest.Result();
    }

    /**
     * Create an instance of {@link XImmunization }
     * 
     */
    public XImmunization createXImmunization() {
        return new XImmunization();
    }

    /**
     * Create an instance of {@link XAllergy }
     * 
     */
    public XAllergy createXAllergy() {
        return new XAllergy();
    }

    /**
     * Create an instance of {@link XAccount }
     * 
     */
    public XAccount createXAccount() {
        return new XAccount();
    }

    /**
     * Create an instance of {@link XRecord }
     * 
     */
    public XRecord createXRecord() {
        return new XRecord();
    }

    /**
     * Create an instance of {@link XReport }
     * 
     */
    public XReport createXReport() {
        return new XReport();
    }

    /**
     * Create an instance of {@link XDocumentMeta }
     * 
     */
    public XDocumentMeta createXDocumentMeta() {
        return new XDocumentMeta();
    }

    /**
     * Create an instance of {@link XReports.Summary }
     * 
     */
    public XReports.Summary createXReportsSummary() {
        return new XReports.Summary();
    }

    /**
     * Create an instance of {@link XDocumentMetaList }
     * 
     */
    public XDocumentMetaList createXDocumentMetaList() {
        return new XDocumentMetaList();
    }

    /**
     * Create an instance of {@link XResultOk }
     * 
     */
    public XResultOk createXResultOk() {
        return new XResultOk();
    }

    /**
     * Create an instance of {@link XDocumentStatusHistory }
     * 
     */
    public XDocumentStatusHistory createXDocumentStatusHistory() {
        return new XDocumentStatusHistory();
    }

    /**
     * Create an instance of {@link XRelation }
     * 
     */
    public XRelation createXRelation() {
        return new XRelation();
    }

    /**
     * Create an instance of {@link XDocumentStatus }
     * 
     */
    public XDocumentStatus createXDocumentStatus() {
        return new XDocumentStatus();
    }

    /**
     * Create an instance of {@link XPrincipal }
     * 
     */
    public XPrincipal createXPrincipal() {
        return new XPrincipal();
    }

    /**
     * Create an instance of {@link XEquipment }
     * 
     */
    public XEquipment createXEquipment() {
        return new XEquipment();
    }

    /**
     * Create an instance of {@link XSchoolForm }
     * 
     */
    public XSchoolForm createXSchoolForm() {
        return new XSchoolForm();
    }

    /**
     * Create an instance of {@link XContact.Name }
     * 
     */
    public XContact.Name createXContactName() {
        return new XContact.Name();
    }

    /**
     * Create an instance of {@link XContact.Email }
     * 
     */
    public XContact.Email createXContactEmail() {
        return new XContact.Email();
    }

    /**
     * Create an instance of {@link XContact.Address }
     * 
     */
    public XContact.Address createXContactAddress() {
        return new XContact.Address();
    }

    /**
     * Create an instance of {@link XContact.Location }
     * 
     */
    public XContact.Location createXContactLocation() {
        return new XContact.Location();
    }

    /**
     * Create an instance of {@link XContact.PhoneNumber }
     * 
     */
    public XContact.PhoneNumber createXContactPhoneNumber() {
        return new XContact.PhoneNumber();
    }

    /**
     * Create an instance of {@link XContact.InstantMessengerName }
     * 
     */
    public XContact.InstantMessengerName createXContactInstantMessengerName() {
        return new XContact.InstantMessengerName();
    }

    /**
     * Create an instance of {@link XVitalSign }
     * 
     */
    public XVitalSign createXVitalSign() {
        return new XVitalSign();
    }

    /**
     * Create an instance of {@link XProcedure }
     * 
     */
    public XProcedure createXProcedure() {
        return new XProcedure();
    }

    /**
     * Create an instance of {@link XSimpleClinicalNote }
     * 
     */
    public XSimpleClinicalNote createXSimpleClinicalNote() {
        return new XSimpleClinicalNote();
    }

    /**
     * Create an instance of {@link XCodedValue }
     * 
     */
    public XCodedValue createXCodedValue() {
        return new XCodedValue();
    }

    /**
     * Create an instance of {@link XSignature }
     * 
     */
    public XSignature createXSignature() {
        return new XSignature();
    }

    /**
     * Create an instance of {@link XDemographics }
     * 
     */
    public XDemographics createXDemographics() {
        return new XDemographics();
    }

    /**
     * Create an instance of {@link XAsthmaActionPlan }
     * 
     */
    public XAsthmaActionPlan createXAsthmaActionPlan() {
        return new XAsthmaActionPlan();
    }

    /**
     * Create an instance of {@link XMedication }
     * 
     */
    public XMedication createXMedication() {
        return new XMedication();
    }

    /**
     * Create an instance of {@link XProblem }
     * 
     */
    public XProblem createXProblem() {
        return new XProblem();
    }

    /**
     * Create an instance of {@link XLab }
     * 
     */
    public XLab createXLab() {
        return new XLab();
    }

    /**
     * Create an instance of {@link XLabProvider }
     * 
     */
    public XLabProvider createXLabProvider() {
        return new XLabProvider();
    }

    /**
     * Create an instance of {@link XLabPanel }
     * 
     */
    public XLabPanel createXLabPanel() {
        return new XLabPanel();
    }

    /**
     * Create an instance of {@link XLabTest }
     * 
     */
    public XLabTest createXLabTest() {
        return new XLabTest();
    }

    /**
     * Create an instance of {@link XLabReport }
     * 
     */
    public XLabReport createXLabReport() {
        return new XLabReport();
    }

    /**
     * Create an instance of {@link XRange }
     * 
     */
    public XRange createXRange() {
        return new XRange();
    }

    /**
     * Create an instance of {@link XSingleResultLabTest }
     * 
     */
    public XSingleResultLabTest createXSingleResultLabTest() {
        return new XSingleResultLabTest();
    }

    /**
     * Create an instance of {@link XResultInRange }
     * 
     */
    public XResultInRange createXResultInRange() {
        return new XResultInRange();
    }

    /**
     * Create an instance of {@link XAnyMedical }
     * 
     */
    public XAnyMedical createXAnyMedical() {
        return new XAnyMedical();
    }

    /**
     * Create an instance of {@link XPrescription }
     * 
     */
    public XPrescription createXPrescription() {
        return new XPrescription();
    }

    /**
     * Create an instance of {@link XValueAndUnit }
     * 
     */
    public XValueAndUnit createXValueAndUnit() {
        return new XValueAndUnit();
    }

    /**
     * Create an instance of {@link XConcentration }
     * 
     */
    public XConcentration createXConcentration() {
        return new XConcentration();
    }

    /**
     * Create an instance of {@link XValueOrRange }
     * 
     */
    public XValueOrRange createXValueOrRange() {
        return new XValueOrRange();
    }

    /**
     * Create an instance of {@link XProvider }
     * 
     */
    public XProvider createXProvider() {
        return new XProvider();
    }

    /**
     * Create an instance of {@link XResultInSet.Option }
     * 
     */
    public XResultInSet.Option createXResultInSetOption() {
        return new XResultInSet.Option();
    }

    /**
     * Create an instance of {@link XMicroWithCultureLabTest.Observation }
     * 
     */
    public XMicroWithCultureLabTest.Observation createXMicroWithCultureLabTestObservation() {
        return new XMicroWithCultureLabTest.Observation();
    }

    /**
     * Create an instance of {@link XMicroWithCultureLabTest.Result.Sensitivity }
     * 
     */
    public XMicroWithCultureLabTest.Result.Sensitivity createXMicroWithCultureLabTestResultSensitivity() {
        return new XMicroWithCultureLabTest.Result.Sensitivity();
    }

    /**
     * Create an instance of {@link XImmunization.Vaccine }
     * 
     */
    public XImmunization.Vaccine createXImmunizationVaccine() {
        return new XImmunization.Vaccine();
    }

    /**
     * Create an instance of {@link XAllergy.Allergen }
     * 
     */
    public XAllergy.Allergen createXAllergyAllergen() {
        return new XAllergy.Allergen();
    }

    /**
     * Create an instance of {@link XAccount.AuthSystem }
     * 
     */
    public XAccount.AuthSystem createXAccountAuthSystem() {
        return new XAccount.AuthSystem();
    }

    /**
     * Create an instance of {@link XRecord.Contact }
     * 
     */
    public XRecord.Contact createXRecordContact() {
        return new XRecord.Contact();
    }

    /**
     * Create an instance of {@link XRecord.Demographics }
     * 
     */
    public XRecord.Demographics createXRecordDemographics() {
        return new XRecord.Demographics();
    }

    /**
     * Create an instance of {@link XReport.Meta }
     * 
     */
    public XReport.Meta createXReportMeta() {
        return new XReport.Meta();
    }

    /**
     * Create an instance of {@link XDocumentMeta.ReplacedBy }
     * 
     */
    public XDocumentMeta.ReplacedBy createXDocumentMetaReplacedBy() {
        return new XDocumentMeta.ReplacedBy();
    }

    /**
     * Create an instance of {@link XDocumentMeta.Replaces }
     * 
     */
    public XDocumentMeta.Replaces createXDocumentMetaReplaces() {
        return new XDocumentMeta.Replaces();
    }

    /**
     * Create an instance of {@link XDocumentMeta.Original }
     * 
     */
    public XDocumentMeta.Original createXDocumentMetaOriginal() {
        return new XDocumentMeta.Original();
    }

    /**
     * Create an instance of {@link XDocumentMeta.Latest }
     * 
     */
    public XDocumentMeta.Latest createXDocumentMetaLatest() {
        return new XDocumentMeta.Latest();
    }

    /**
     * Create an instance of {@link XDocumentMeta.RelatesTo }
     * 
     */
    public XDocumentMeta.RelatesTo createXDocumentMetaRelatesTo() {
        return new XDocumentMeta.RelatesTo();
    }

    /**
     * Create an instance of {@link XDocumentMeta.IsRelatedFrom }
     * 
     */
    public XDocumentMeta.IsRelatedFrom createXDocumentMetaIsRelatedFrom() {
        return new XDocumentMeta.IsRelatedFrom();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XDocumentMeta }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Document")
    public JAXBElement<XDocumentMeta> createDocument(XDocumentMeta value) {
        return new JAXBElement<XDocumentMeta>(_Document_QNAME, XDocumentMeta.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMedication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://indivo.org/vocab/xml/documents#", name = "Medication")
    public JAXBElement<XMedication> createMedication(XMedication value) {
        return new JAXBElement<XMedication>(_Medication_QNAME, XMedication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XProblem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://indivo.org/vocab/xml/documents#", name = "Problem")
    public JAXBElement<XProblem> createProblem(XProblem value) {
        return new JAXBElement<XProblem>(_Problem_QNAME, XProblem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAccount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Account")
    public JAXBElement<XAccount> createAccount(XAccount value) {
        return new JAXBElement<XAccount>(_Account_QNAME, XAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAllergy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://indivo.org/vocab/xml/documents#", name = "Allergy")
    public JAXBElement<XAllergy> createAllergy(XAllergy value) {
        return new JAXBElement<XAllergy>(_Allergy_QNAME, XAllergy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XVitalSign }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://indivo.org/vocab/xml/documents#", name = "VitalSign")
    public JAXBElement<XVitalSign> createVitalSign(XVitalSign value) {
        return new JAXBElement<XVitalSign>(_VitalSign_QNAME, XVitalSign.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XRecord }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Record")
    public JAXBElement<XRecord> createRecord(XRecord value) {
        return new JAXBElement<XRecord>(_Record_QNAME, XRecord.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XEquipment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://indivo.org/vocab/xml/documents#", name = "Equipment")
    public JAXBElement<XEquipment> createEquipment(XEquipment value) {
        return new JAXBElement<XEquipment>(_Equipment_QNAME, XEquipment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XDocumentMetaList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Documents")
    public JAXBElement<XDocumentMetaList> createDocuments(XDocumentMetaList value) {
        return new JAXBElement<XDocumentMetaList>(_Documents_QNAME, XDocumentMetaList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XResultOk }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ok")
    public JAXBElement<XResultOk> createOk(XResultOk value) {
        return new JAXBElement<XResultOk>(_Ok_QNAME, XResultOk.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XImmunization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://indivo.org/vocab/xml/documents#", name = "Immunization")
    public JAXBElement<XImmunization> createImmunization(XImmunization value) {
        return new JAXBElement<XImmunization>(_Immunization_QNAME, XImmunization.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XDocumentStatusHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DocumentStatusHistory")
    public JAXBElement<XDocumentStatusHistory> createDocumentStatusHistory(XDocumentStatusHistory value) {
        return new JAXBElement<XDocumentStatusHistory>(_DocumentStatusHistory_QNAME, XDocumentStatusHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XProcedure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://indivo.org/vocab/xml/documents#", name = "Procedure")
    public JAXBElement<XProcedure> createProcedure(XProcedure value) {
        return new JAXBElement<XProcedure>(_Procedure_QNAME, XProcedure.class, null, value);
    }

}
