//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 03:34:16 PM CEST 
//


package com.orange.jlinx.document.x;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Allergy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Allergy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dateDiagnosed" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="diagnosedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="allergen">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type" type="{http://indivo.org/vocab/xml/documents#}CodedValue" minOccurs="0"/>
 *                   &lt;element name="name" type="{http://indivo.org/vocab/xml/documents#}CodedValue"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reaction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specifics" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Allergy", propOrder = {
    "dateDiagnosed",
    "diagnosedBy",
    "allergen",
    "reaction",
    "specifics"
})
public class XAllergy {

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateDiagnosed;
    protected String diagnosedBy;
    @XmlElement(required = true)
    protected XAllergy.Allergen allergen;
    protected String reaction;
    protected String specifics;

    /**
     * Gets the value of the dateDiagnosed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getDateDiagnosed() {
        return dateDiagnosed;
    }

    /**
     * Sets the value of the dateDiagnosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateDiagnosed(XMLGregorianCalendar value) {
        this.dateDiagnosed = value;
    }

    /**
     * Gets the value of the diagnosedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosedBy() {
        return diagnosedBy;
    }

    /**
     * Sets the value of the diagnosedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosedBy(String value) {
        this.diagnosedBy = value;
    }

    /**
     * Gets the value of the allergen property.
     * 
     * @return
     *     possible object is
     *     {@link XAllergy.Allergen }
     *     
     */
    public XAllergy.Allergen getAllergen() {
        return allergen;
    }

    /**
     * Sets the value of the allergen property.
     * 
     * @param value
     *     allowed object is
     *     {@link XAllergy.Allergen }
     *     
     */
    public void setAllergen(XAllergy.Allergen value) {
        this.allergen = value;
    }

    /**
     * Gets the value of the reaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReaction() {
        return reaction;
    }

    /**
     * Sets the value of the reaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReaction(String value) {
        this.reaction = value;
    }

    /**
     * Gets the value of the specifics property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecifics() {
        return specifics;
    }

    /**
     * Sets the value of the specifics property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecifics(String value) {
        this.specifics = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type" type="{http://indivo.org/vocab/xml/documents#}CodedValue" minOccurs="0"/>
     *         &lt;element name="name" type="{http://indivo.org/vocab/xml/documents#}CodedValue"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "name"
    })
    public static class Allergen {

        protected XCodedValue type;
        @XmlElement(required = true)
        protected XCodedValue name;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link XCodedValue }
         *     
         */
        public XCodedValue getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link XCodedValue }
         *     
         */
        public void setType(XCodedValue value) {
            this.type = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link XCodedValue }
         *     
         */
        public XCodedValue getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link XCodedValue }
         *     
         */
        public void setName(XCodedValue value) {
            this.name = value;
        }

    }

}
