//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 03:34:16 PM CEST 
//


package com.orange.jlinx.document.x;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dateMeasured" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="labType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="laboratory" type="{http://indivo.org/vocab/xml/documents#}LabProvider" minOccurs="0"/>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="firstPanelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="firstLabTestName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="firstLabTestValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="normalRangeMinimum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="normalRangeMaximum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nonCriticalRangeMinimum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nonCriticalRangeMaximum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dateMeasured",
    "labType",
    "laboratory",
    "comments",
    "firstPanelName",
    "firstLabTestName",
    "firstLabTestValue",
    "normalRangeMinimum",
    "normalRangeMaximum",
    "nonCriticalRangeMinimum",
    "nonCriticalRangeMaximum"
})
@XmlRootElement(name = "LabReport")
public class XLabReport {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateMeasured;
    @XmlElement(required = true)
    protected String labType;
    protected XLabProvider laboratory;
    protected String comments;
    protected String firstPanelName;
    protected String firstLabTestName;
    protected String firstLabTestValue;
    protected String normalRangeMinimum;
    protected String normalRangeMaximum;
    protected String nonCriticalRangeMinimum;
    protected String nonCriticalRangeMaximum;

    /**
     * Gets the value of the dateMeasured property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getDateMeasured() {
        return dateMeasured;
    }

    /**
     * Sets the value of the dateMeasured property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateMeasured(XMLGregorianCalendar value) {
        this.dateMeasured = value;
    }

    /**
     * Gets the value of the labType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabType() {
        return labType;
    }

    /**
     * Sets the value of the labType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabType(String value) {
        this.labType = value;
    }

    /**
     * Gets the value of the laboratory property.
     * 
     * @return
     *     possible object is
     *     {@link XLabProvider }
     *     
     */
    public XLabProvider getLaboratory() {
        return laboratory;
    }

    /**
     * Sets the value of the laboratory property.
     * 
     * @param value
     *     allowed object is
     *     {@link XLabProvider }
     *     
     */
    public void setLaboratory(XLabProvider value) {
        this.laboratory = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the firstPanelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstPanelName() {
        return firstPanelName;
    }

    /**
     * Sets the value of the firstPanelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstPanelName(String value) {
        this.firstPanelName = value;
    }

    /**
     * Gets the value of the firstLabTestName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstLabTestName() {
        return firstLabTestName;
    }

    /**
     * Sets the value of the firstLabTestName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstLabTestName(String value) {
        this.firstLabTestName = value;
    }

    /**
     * Gets the value of the firstLabTestValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstLabTestValue() {
        return firstLabTestValue;
    }

    /**
     * Sets the value of the firstLabTestValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstLabTestValue(String value) {
        this.firstLabTestValue = value;
    }

    /**
     * Gets the value of the normalRangeMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalRangeMinimum() {
        return normalRangeMinimum;
    }

    /**
     * Sets the value of the normalRangeMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalRangeMinimum(String value) {
        this.normalRangeMinimum = value;
    }

    /**
     * Gets the value of the normalRangeMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalRangeMaximum() {
        return normalRangeMaximum;
    }

    /**
     * Sets the value of the normalRangeMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalRangeMaximum(String value) {
        this.normalRangeMaximum = value;
    }

    /**
     * Gets the value of the nonCriticalRangeMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonCriticalRangeMinimum() {
        return nonCriticalRangeMinimum;
    }

    /**
     * Sets the value of the nonCriticalRangeMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonCriticalRangeMinimum(String value) {
        this.nonCriticalRangeMinimum = value;
    }

    /**
     * Gets the value of the nonCriticalRangeMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonCriticalRangeMaximum() {
        return nonCriticalRangeMaximum;
    }

    /**
     * Sets the value of the nonCriticalRangeMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonCriticalRangeMaximum(String value) {
        this.nonCriticalRangeMaximum = value;
    }

}
