//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 03:34:16 PM CEST 
//


package com.orange.jlinx.document.x;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MicroWithCultureLabTest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MicroWithCultureLabTest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://indivo.org/vocab/xml/documents#}LabTest">
 *       &lt;sequence>
 *         &lt;element name="source" type="{http://indivo.org/vocab/xml/documents#}CodedValue"/>
 *         &lt;element name="observation" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="microbialDensity" type="{http://indivo.org/vocab/xml/documents#}Concentration" minOccurs="0"/>
 *                   &lt;element name="organism" type="{http://indivo.org/vocab/xml/documents#}CodedValue" minOccurs="0"/>
 *                   &lt;element name="extendedDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cultureCondition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="gram" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="morphology" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="isolate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="identity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="result" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="organism" type="{http://indivo.org/vocab/xml/documents#}CodedValue"/>
 *                   &lt;element name="sensitivity" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="antibiotic" type="{http://indivo.org/vocab/xml/documents#}CodedValue"/>
 *                             &lt;element name="MIC" type="{http://indivo.org/vocab/xml/documents#}Concentration" minOccurs="0"/>
 *                             &lt;element name="interpretation" type="{http://indivo.org/vocab/xml/documents#}CodedValue"/>
 *                             &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="interpretation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="isolate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="identity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MicroWithCultureLabTest", propOrder = {
    "source",
    "observation",
    "result"
})
public class XMicroWithCultureLabTest
    extends XLabTest
{

    @XmlElement(required = true)
    protected XCodedValue source;
    protected List<XMicroWithCultureLabTest.Observation> observation;
    protected List<XMicroWithCultureLabTest.Result> result;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link XCodedValue }
     *     
     */
    public XCodedValue getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link XCodedValue }
     *     
     */
    public void setSource(XCodedValue value) {
        this.source = value;
    }

    /**
     * Gets the value of the observation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the observation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObservation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMicroWithCultureLabTest.Observation }
     * 
     * 
     */
    public List<XMicroWithCultureLabTest.Observation> getObservation() {
        if (observation == null) {
            observation = new ArrayList<XMicroWithCultureLabTest.Observation>();
        }
        return this.observation;
    }

    /**
     * Gets the value of the result property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the result property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMicroWithCultureLabTest.Result }
     * 
     * 
     */
    public List<XMicroWithCultureLabTest.Result> getResult() {
        if (result == null) {
            result = new ArrayList<XMicroWithCultureLabTest.Result>();
        }
        return this.result;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="microbialDensity" type="{http://indivo.org/vocab/xml/documents#}Concentration" minOccurs="0"/>
     *         &lt;element name="organism" type="{http://indivo.org/vocab/xml/documents#}CodedValue" minOccurs="0"/>
     *         &lt;element name="extendedDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cultureCondition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="gram" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="morphology" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="isolate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="identity" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "time",
        "microbialDensity",
        "organism",
        "extendedDescription",
        "cultureCondition",
        "gram",
        "morphology",
        "organization",
        "comments"
    })
    public static class Observation {

        @XmlElement(required = true, type = String.class)
        @XmlJavaTypeAdapter(Adapter1 .class)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar time;
        protected XConcentration microbialDensity;
        protected XCodedValue organism;
        protected String extendedDescription;
        protected String cultureCondition;
        protected Boolean gram;
        protected String morphology;
        protected String organization;
        protected String comments;
        @XmlAttribute(name = "isolate", required = true)
        protected String isolate;
        @XmlAttribute(name = "identity")
        protected String identity;

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public XMLGregorianCalendar getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTime(XMLGregorianCalendar value) {
            this.time = value;
        }

        /**
         * Gets the value of the microbialDensity property.
         * 
         * @return
         *     possible object is
         *     {@link XConcentration }
         *     
         */
        public XConcentration getMicrobialDensity() {
            return microbialDensity;
        }

        /**
         * Sets the value of the microbialDensity property.
         * 
         * @param value
         *     allowed object is
         *     {@link XConcentration }
         *     
         */
        public void setMicrobialDensity(XConcentration value) {
            this.microbialDensity = value;
        }

        /**
         * Gets the value of the organism property.
         * 
         * @return
         *     possible object is
         *     {@link XCodedValue }
         *     
         */
        public XCodedValue getOrganism() {
            return organism;
        }

        /**
         * Sets the value of the organism property.
         * 
         * @param value
         *     allowed object is
         *     {@link XCodedValue }
         *     
         */
        public void setOrganism(XCodedValue value) {
            this.organism = value;
        }

        /**
         * Gets the value of the extendedDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtendedDescription() {
            return extendedDescription;
        }

        /**
         * Sets the value of the extendedDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtendedDescription(String value) {
            this.extendedDescription = value;
        }

        /**
         * Gets the value of the cultureCondition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCultureCondition() {
            return cultureCondition;
        }

        /**
         * Sets the value of the cultureCondition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCultureCondition(String value) {
            this.cultureCondition = value;
        }

        /**
         * Gets the value of the gram property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isGram() {
            return gram;
        }

        /**
         * Sets the value of the gram property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setGram(Boolean value) {
            this.gram = value;
        }

        /**
         * Gets the value of the morphology property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMorphology() {
            return morphology;
        }

        /**
         * Sets the value of the morphology property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMorphology(String value) {
            this.morphology = value;
        }

        /**
         * Gets the value of the organization property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrganization() {
            return organization;
        }

        /**
         * Sets the value of the organization property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrganization(String value) {
            this.organization = value;
        }

        /**
         * Gets the value of the comments property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComments() {
            return comments;
        }

        /**
         * Sets the value of the comments property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComments(String value) {
            this.comments = value;
        }

        /**
         * Gets the value of the isolate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsolate() {
            return isolate;
        }

        /**
         * Sets the value of the isolate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsolate(String value) {
            this.isolate = value;
        }

        /**
         * Gets the value of the identity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentity() {
            return identity;
        }

        /**
         * Sets the value of the identity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentity(String value) {
            this.identity = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="organism" type="{http://indivo.org/vocab/xml/documents#}CodedValue"/>
     *         &lt;element name="sensitivity" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="antibiotic" type="{http://indivo.org/vocab/xml/documents#}CodedValue"/>
     *                   &lt;element name="MIC" type="{http://indivo.org/vocab/xml/documents#}Concentration" minOccurs="0"/>
     *                   &lt;element name="interpretation" type="{http://indivo.org/vocab/xml/documents#}CodedValue"/>
     *                   &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="interpretation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="isolate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="identity" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organism",
        "sensitivity",
        "interpretation",
        "comments"
    })
    public static class Result {

        @XmlElement(required = true)
        protected XCodedValue organism;
        protected List<XMicroWithCultureLabTest.Result.Sensitivity> sensitivity;
        protected String interpretation;
        protected String comments;
        @XmlAttribute(name = "isolate", required = true)
        protected String isolate;
        @XmlAttribute(name = "identity")
        protected String identity;

        /**
         * Gets the value of the organism property.
         * 
         * @return
         *     possible object is
         *     {@link XCodedValue }
         *     
         */
        public XCodedValue getOrganism() {
            return organism;
        }

        /**
         * Sets the value of the organism property.
         * 
         * @param value
         *     allowed object is
         *     {@link XCodedValue }
         *     
         */
        public void setOrganism(XCodedValue value) {
            this.organism = value;
        }

        /**
         * Gets the value of the sensitivity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sensitivity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSensitivity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XMicroWithCultureLabTest.Result.Sensitivity }
         * 
         * 
         */
        public List<XMicroWithCultureLabTest.Result.Sensitivity> getSensitivity() {
            if (sensitivity == null) {
                sensitivity = new ArrayList<XMicroWithCultureLabTest.Result.Sensitivity>();
            }
            return this.sensitivity;
        }

        /**
         * Gets the value of the interpretation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterpretation() {
            return interpretation;
        }

        /**
         * Sets the value of the interpretation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterpretation(String value) {
            this.interpretation = value;
        }

        /**
         * Gets the value of the comments property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComments() {
            return comments;
        }

        /**
         * Sets the value of the comments property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComments(String value) {
            this.comments = value;
        }

        /**
         * Gets the value of the isolate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsolate() {
            return isolate;
        }

        /**
         * Sets the value of the isolate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsolate(String value) {
            this.isolate = value;
        }

        /**
         * Gets the value of the identity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentity() {
            return identity;
        }

        /**
         * Sets the value of the identity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentity(String value) {
            this.identity = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="antibiotic" type="{http://indivo.org/vocab/xml/documents#}CodedValue"/>
         *         &lt;element name="MIC" type="{http://indivo.org/vocab/xml/documents#}Concentration" minOccurs="0"/>
         *         &lt;element name="interpretation" type="{http://indivo.org/vocab/xml/documents#}CodedValue"/>
         *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "antibiotic",
            "mic",
            "interpretation",
            "comments"
        })
        public static class Sensitivity {

            @XmlElement(required = true)
            protected XCodedValue antibiotic;
            @XmlElement(name = "MIC")
            protected XConcentration mic;
            @XmlElement(required = true)
            protected XCodedValue interpretation;
            protected String comments;

            /**
             * Gets the value of the antibiotic property.
             * 
             * @return
             *     possible object is
             *     {@link XCodedValue }
             *     
             */
            public XCodedValue getAntibiotic() {
                return antibiotic;
            }

            /**
             * Sets the value of the antibiotic property.
             * 
             * @param value
             *     allowed object is
             *     {@link XCodedValue }
             *     
             */
            public void setAntibiotic(XCodedValue value) {
                this.antibiotic = value;
            }

            /**
             * Gets the value of the mic property.
             * 
             * @return
             *     possible object is
             *     {@link XConcentration }
             *     
             */
            public XConcentration getMIC() {
                return mic;
            }

            /**
             * Sets the value of the mic property.
             * 
             * @param value
             *     allowed object is
             *     {@link XConcentration }
             *     
             */
            public void setMIC(XConcentration value) {
                this.mic = value;
            }

            /**
             * Gets the value of the interpretation property.
             * 
             * @return
             *     possible object is
             *     {@link XCodedValue }
             *     
             */
            public XCodedValue getInterpretation() {
                return interpretation;
            }

            /**
             * Sets the value of the interpretation property.
             * 
             * @param value
             *     allowed object is
             *     {@link XCodedValue }
             *     
             */
            public void setInterpretation(XCodedValue value) {
                this.interpretation = value;
            }

            /**
             * Gets the value of the comments property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComments() {
                return comments;
            }

            /**
             * Sets the value of the comments property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComments(String value) {
                this.comments = value;
            }

        }

    }

}
