//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 03:34:16 PM CEST 
//


package com.orange.jlinx.document.x;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Summary">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="total_document_count" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="limit" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="order_by" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Report" type="{}Report" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "summary",
    "report"
})
@XmlRootElement(name = "Reports", namespace = "")
public class XReports {

    @XmlElement(name = "Summary", namespace = "", required = true)
    protected XReports.Summary summary;
    @XmlElement(name = "Report", namespace = "", required = true)
    protected List<XReport> report;

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link XReports.Summary }
     *     
     */
    public XReports.Summary getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link XReports.Summary }
     *     
     */
    public void setSummary(XReports.Summary value) {
        this.summary = value;
    }

    /**
     * Gets the value of the report property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the report property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XReport }
     * 
     * 
     */
    public List<XReport> getReport() {
        if (report == null) {
            report = new ArrayList<XReport>();
        }
        return this.report;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="total_document_count" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="limit" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="order_by" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Summary {

        @XmlAttribute(name = "total_document_count")
        @XmlJavaTypeAdapter(Adapter2 .class)
        @XmlSchemaType(name = "integer")
        protected Integer totalDocumentCount;
        @XmlAttribute(name = "limit")
        @XmlJavaTypeAdapter(Adapter2 .class)
        @XmlSchemaType(name = "integer")
        protected Integer limit;
        @XmlAttribute(name = "offset")
        @XmlJavaTypeAdapter(Adapter2 .class)
        @XmlSchemaType(name = "integer")
        protected Integer offset;
        @XmlAttribute(name = "order_by")
        protected String orderBy;

        /**
         * Gets the value of the totalDocumentCount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Integer getTotalDocumentCount() {
            return totalDocumentCount;
        }

        /**
         * Sets the value of the totalDocumentCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTotalDocumentCount(Integer value) {
            this.totalDocumentCount = value;
        }

        /**
         * Gets the value of the limit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Integer getLimit() {
            return limit;
        }

        /**
         * Sets the value of the limit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLimit(Integer value) {
            this.limit = value;
        }

        /**
         * Gets the value of the offset property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Integer getOffset() {
            return offset;
        }

        /**
         * Sets the value of the offset property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOffset(Integer value) {
            this.offset = value;
        }

        /**
         * Gets the value of the orderBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderBy() {
            return orderBy;
        }

        /**
         * Sets the value of the orderBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderBy(String value) {
            this.orderBy = value;
        }

    }

}
