//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 03:34:16 PM CEST 
//


package com.orange.jlinx.document.x;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResultInRange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultInRange">
 *   &lt;complexContent>
 *     &lt;extension base="{http://indivo.org/vocab/xml/documents#}Result">
 *       &lt;sequence>
 *         &lt;element name="valueAndUnit" type="{http://indivo.org/vocab/xml/documents#}ValueAndUnit"/>
 *         &lt;element name="normalRange" type="{http://indivo.org/vocab/xml/documents#}Range" minOccurs="0"/>
 *         &lt;element name="nonCriticalRange" type="{http://indivo.org/vocab/xml/documents#}Range" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultInRange", propOrder = {
    "valueAndUnit",
    "normalRange",
    "nonCriticalRange"
})
public class XResultInRange
    extends XResult
{

    @XmlElement(required = true)
    protected XValueAndUnit valueAndUnit;
    protected XRange normalRange;
    protected XRange nonCriticalRange;

    /**
     * Gets the value of the valueAndUnit property.
     * 
     * @return
     *     possible object is
     *     {@link XValueAndUnit }
     *     
     */
    public XValueAndUnit getValueAndUnit() {
        return valueAndUnit;
    }

    /**
     * Sets the value of the valueAndUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link XValueAndUnit }
     *     
     */
    public void setValueAndUnit(XValueAndUnit value) {
        this.valueAndUnit = value;
    }

    /**
     * Gets the value of the normalRange property.
     * 
     * @return
     *     possible object is
     *     {@link XRange }
     *     
     */
    public XRange getNormalRange() {
        return normalRange;
    }

    /**
     * Sets the value of the normalRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link XRange }
     *     
     */
    public void setNormalRange(XRange value) {
        this.normalRange = value;
    }

    /**
     * Gets the value of the nonCriticalRange property.
     * 
     * @return
     *     possible object is
     *     {@link XRange }
     *     
     */
    public XRange getNonCriticalRange() {
        return nonCriticalRange;
    }

    /**
     * Sets the value of the nonCriticalRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link XRange }
     *     
     */
    public void setNonCriticalRange(XRange value) {
        this.nonCriticalRange = value;
    }

}
