//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 03:34:16 PM CEST 
//


package com.orange.jlinx.document.x;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dateOfVisit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="finalizedAt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="visitType" type="{http://indivo.org/vocab/xml/documents#}CodedValue" minOccurs="0"/>
 *         &lt;element name="visitLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specialty" type="{http://indivo.org/vocab/xml/documents#}CodedValue" minOccurs="0"/>
 *         &lt;element name="signature" type="{http://indivo.org/vocab/xml/documents#}Signature" maxOccurs="unbounded"/>
 *         &lt;element name="chiefComplaint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dateOfVisit",
    "finalizedAt",
    "visitType",
    "visitLocation",
    "specialty",
    "signature",
    "chiefComplaint",
    "content"
})
@XmlRootElement(name = "SimpleClinicalNote")
public class XSimpleClinicalNote {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateOfVisit;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar finalizedAt;
    protected XCodedValue visitType;
    protected String visitLocation;
    protected XCodedValue specialty;
    @XmlElement(required = true)
    protected List<XSignature> signature;
    protected String chiefComplaint;
    protected String content;

    /**
     * Gets the value of the dateOfVisit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getDateOfVisit() {
        return dateOfVisit;
    }

    /**
     * Sets the value of the dateOfVisit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfVisit(XMLGregorianCalendar value) {
        this.dateOfVisit = value;
    }

    /**
     * Gets the value of the finalizedAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getFinalizedAt() {
        return finalizedAt;
    }

    /**
     * Sets the value of the finalizedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalizedAt(XMLGregorianCalendar value) {
        this.finalizedAt = value;
    }

    /**
     * Gets the value of the visitType property.
     * 
     * @return
     *     possible object is
     *     {@link XCodedValue }
     *     
     */
    public XCodedValue getVisitType() {
        return visitType;
    }

    /**
     * Sets the value of the visitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link XCodedValue }
     *     
     */
    public void setVisitType(XCodedValue value) {
        this.visitType = value;
    }

    /**
     * Gets the value of the visitLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitLocation() {
        return visitLocation;
    }

    /**
     * Sets the value of the visitLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitLocation(String value) {
        this.visitLocation = value;
    }

    /**
     * Gets the value of the specialty property.
     * 
     * @return
     *     possible object is
     *     {@link XCodedValue }
     *     
     */
    public XCodedValue getSpecialty() {
        return specialty;
    }

    /**
     * Sets the value of the specialty property.
     * 
     * @param value
     *     allowed object is
     *     {@link XCodedValue }
     *     
     */
    public void setSpecialty(XCodedValue value) {
        this.specialty = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XSignature }
     * 
     * 
     */
    public List<XSignature> getSignature() {
        if (signature == null) {
            signature = new ArrayList<XSignature>();
        }
        return this.signature;
    }

    /**
     * Gets the value of the chiefComplaint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChiefComplaint() {
        return chiefComplaint;
    }

    /**
     * Sets the value of the chiefComplaint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChiefComplaint(String value) {
        this.chiefComplaint = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

}
