//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 03:34:16 PM CEST 
//


package com.orange.jlinx.document.x;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValueOrRange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValueOrRange">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="value" type="{http://indivo.org/vocab/xml/documents#}ValueAndUnit"/>
 *         &lt;element name="range" type="{http://indivo.org/vocab/xml/documents#}Range"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValueOrRange", propOrder = {
    "value",
    "range"
})
@XmlSeeAlso({
    XConcentration.class
})
public class XValueOrRange {

    protected XValueAndUnit value;
    protected XRange range;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link XValueAndUnit }
     *     
     */
    public XValueAndUnit getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link XValueAndUnit }
     *     
     */
    public void setValue(XValueAndUnit value) {
        this.value = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * @return
     *     possible object is
     *     {@link XRange }
     *     
     */
    public XRange getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link XRange }
     *     
     */
    public void setRange(XRange value) {
        this.range = value;
    }

}
